inherit_from:
  - .rubocop.unhound.yml

Metrics/LineLength:
  Max: 100

Style/DotPosition:
  EnforcedStyle: trailing

Style/Documentation:
  Enabled: false

Style/IndentHash:
  EnforcedStyle: consistent

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/WordArray:
  Enabled: false

Style/RegexpLiteral:
  AllowInnerSlashes: true

Style/ClassAndModuleChildren:
  EnforcedStyle: compact
