inherit_from:
  - .rubocop.unhound.yml

AllCops:
  Include:
    - '**/Gemfile'
    - '**/Rakefile'
  Exclude:
   - 'vendor/bundle/**/*'
  TargetRubyVersion: 2.1

Metrics/LineLength:
  Max: 100

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Style/DotPosition:
  EnforcedStyle: trailing

Style/Documentation:
  Enabled: false

Style/IndentHash:
  EnforcedStyle: consistent

Style/IfUnlessModifier:
  MaxLineLength: 100

Style/ParallelAssignment:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/WhileUntilModifier:
  MaxLineLength: 100

Style/WordArray:
  Enabled: false

Style/RegexpLiteral:
  AllowInnerSlashes: true

Style/ClassAndModuleChildren:
  EnforcedStyle: compact
