sudo: required
language: ruby
rvm:
  - 2.1.7
  - 2.2.3
  - ruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
services:
  - docker
bundler_args: "--jobs=3 --retry=3 --deployment"
cache: bundler

before_install:
  - gem update bundler
