sudo: required
language: ruby
rvm:
  - 2.1.8
  - 2.2.4
  - 2.3.0
  - ruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
services:
  - docker
bundler_args: "--jobs=3 --retry=3"
cache: bundler

before_install:
  - sudo apt-get update
  - sudo apt-get -o Dpkg::Options::="--force-confnew" install -y docker-engine=1.10.3-0~trusty
  - gem install bundler
  - docker version
