sudo: required
language: ruby
branches:
  except:
    - /^bundle-update-[0-9]{4}-[0-9]{2}-[0-9]{2}-[0-9]{6}+$/
rvm:
  - 2.1.8
  - 2.2.4
  - 2.3.0
  - ruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
services:
  - docker
bundler_args: "--jobs=3 --retry=3"
cache: bundler

before_install:
  - gem install bundler
