sudo: required
language: ruby
rvm:
  - 2.1.8
  - 2.2.4
  - 2.3.0
  - ruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
services:
  - docker
bundler_args: "--jobs=3 --retry=3"
cache: bundler

before_install:
  - gem install bundler
